extend struct HDCore {

    static clearscope string getBatteryIcon(int charge) {
        if (charge > 13) return "CELLA0";
        if (charge > 6)  return "CELLB0";
        if (charge > 0)  return "CELLC0";

        return "CELLD0";
    }

    static clearscope string getMicroCellIcon(int charge) {
        if (charge > 6) return "MCLLA0";
        if (charge > 3) return "MCLLB0";
        if (charge > 0) return "MCLLC0";

        return "MCLLD0";
    }
}