version "4.12"

// Bundled Libraries
#include "zscript/libs/HDZForms/include.zsc"
#include "zscript/libs/HDGutamatics/include.zsc"

// Global Classes
#include "zscript/HDCore/commands/HDCoreCommand.zsc"
#include "zscript/HDCore/ui/CameraContext.zsc"
#include "zscript/HDCore/ui/VectorPrefabs.zsc"

// HDCoreLib
#include "zscript/HDCore/HDCore.zsc"
#include "zscript/HDCore/debug/Debug.zsc"
#include "zscript/HDCore/io/HDCoreInfoReader.zsc"
#include "zscript/HDCore/random/Random.zsc"
#include "zscript/HDCore/sectors/Sectors.zsc"
#include "zscript/HDCore/spawning/AmmoAssociations.zsc"
#include "zscript/HDCore/spawning/SpawnTables.zsc"
#include "zscript/HDCore/ui/DrawBar.zsc"
#include "zscript/HDCore/ui/DrawPrefabs.zsc"

// Event Handlers
#include "zscript/HDCore/events/AmmoBoxSpawnPoolHandler.zsc"
#include "zscript/HDCore/events/AmmoUsageHandler.zsc"
#include "zscript/HDCore/events/BackpackSpawnPoolHandler.zsc"
#include "zscript/HDCore/events/SpawnHandler.zsc"
