version "4.14"

// Bundled Libraries
#include "zscript/libs/HDZForms/include.zsc"
#include "zscript/libs/HDGutamatics/include.zsc"
#include "zscript/libs/HDZJSON/include.zsc"
#include "zscript/libs/HDlibtooltipmenu/include.zsc"
#include "zscript/libs/HDAceCoreLib/include.zsc"

// Base Classes
#include "zscript/HDCore/base/data/providers/DataProvider.zsc"
#include "zscript/HDCore/base/data/providers/FunctionProvider.zsc"
#include "zscript/HDCore/base/events/BaseEventHandler.zsc"
#include "zscript/HDCore/base/events/BaseStaticEventHandler.zsc"
#include "zscript/HDCore/base/weapons/BaseMeleeWeapon.zsc"

// Data Providers
#include "zscript/HDCore/data/providers/StaticProvider.zsc"
#include "zscript/HDCore/data/providers/CVarProvider.zsc"
#include "zscript/HDCore/data/providers/LocalizedStringProvider.zsc"

#include "zscript/HDCore/data/providers/functions/ArithmeticProvider.zsc"
#include "zscript/HDCore/data/providers/functions/BooleanLogicProvider.zsc"
#include "zscript/HDCore/data/providers/functions/ClassExistsProvider.zsc"
#include "zscript/HDCore/data/providers/functions/ConditionalProvider.zsc"
#include "zscript/HDCore/data/providers/functions/GameStatProvider.zsc"
#include "zscript/HDCore/data/providers/functions/LerpProvider.zsc"
#include "zscript/HDCore/data/providers/functions/MapStatProvider.zsc"
#include "zscript/HDCore/data/providers/functions/RandomProvider.zsc"
// #include "zscript/HDCore/data/providers/functions/ServiceProvider.zsc"

// Global Classes
#include "zscript/HDCore/commands/HDCoreCommandParam.zsc"
#include "zscript/HDCore/commands/HDCoreCommand.zsc"
#include "zscript/HDCore/lineTracing/LineTraceData.zsc"
#include "zscript/HDCore/spawning/ClusterSpawner.zsc"
#include "zscript/HDCore/thinkers/GameStatsThinker.zsc"
#include "zscript/HDCore/ui/CameraContext.zsc"
#include "zscript/HDCore/ui/VectorPrefabs.zsc"

// HDCoreLib
#include "zscript/HDCore/HDCore.zsc"
#include "zscript/HDCore/debug/Debug.zsc"
#include "zscript/HDCore/helpers/ClassHelpers.zsc"
#include "zscript/HDCore/helpers/ColorHelpers.zsc"
#include "zscript/HDCore/helpers/InventoryHelpers.zsc"
#include "zscript/HDCore/helpers/ParticleHelpers.zsc"
#include "zscript/HDCore/helpers/PlayerHelpers.zsc"
#include "zscript/HDCore/helpers/SpawningHelpers.zsc"
#include "zscript/HDCore/io/HDCoreInfoReader.zsc"
#include "zscript/HDCore/logging/Logging.zsc"
#include "zscript/HDCore/math/DampedSpring.zsc"
#include "zscript/HDCore/math/ScaledChances.zsc"
#include "zscript/HDCore/random/Random.zsc"
#include "zscript/HDCore/random/WeightedRandomTables.zsc"
#include "zscript/HDCore/sectors/Sectors.zsc"
#include "zscript/HDCore/spawning/AmmoAssociations.zsc"
#include "zscript/HDCore/spawning/DummySpawners.zsc"
#include "zscript/HDCore/spawning/SpawnTables.zsc"
#include "zscript/HDCore/ui/DrawBar.zsc"
#include "zscript/HDCore/ui/DrawPrefabs.zsc"

// Custom Menus
#include "zscript/HDCore/menus/SpawnTableEntryFrame.zsc"
#include "zscript/HDCore/menus/SpawnTableFrame.zsc"
#include "zscript/HDCore/menus/SpawnTableCategoryFrame.zsc"
#include "zscript/HDCore/menus/SpawnTableMenu.zsc"

// Event Handlers
#include "zscript/HDCore/events/AmmoBoxSpawnPoolHandler.zsc"
#include "zscript/HDCore/events/AmmoUsageHandler.zsc"
#include "zscript/HDCore/events/BackpackSpawnPoolHandler.zsc"
#include "zscript/HDCore/events/DeathMatchStartSpawnHandler.zsc"
#include "zscript/HDCore/events/GameStatsHandler.zsc"
#include "zscript/HDCore/events/LineTraceHandler.zsc"
#include "zscript/HDCore/events/RandomSeedHandler.zsc"
#include "zscript/HDCore/events/MapStatsHandler.zsc"
#include "zscript/HDCore/events/SectorSpawnHandler.zsc"
#include "zscript/HDCore/events/SpawnHandler.zsc"
