class HDCoreStaticProvider : HDCoreDataProvider {

    override string getStringValue() {
        return _value;
    }

    override name getNameValue() {
        name name = getStringValue();
        return name;
    }

    override int getIntValue() {
        return _value.toInt(10);
    }

    override double getDoubleValue() {
        return _value.toDouble();
    }

    override bool getBoolValue() {
        return _value == 'true' || _value == 'y' || getIntValue();
    }
}