name: Build PK3
description: Builds the PK3
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: montudor/action-zip@v1
    with:
      args: zip -r "HDCoreLib-${{ env.SUFFIX }}.pk3" . -i graphics/* sprites/* zscript/* CVARINFO HDCINFO LANGUAGE LICENSE MAPINFO README.md ZSCRIPT.zsc
